name: master-latest

on:
  push:
    branches: [ master ]

jobs:
  multiarch-to-dockerhub-latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # Setup qEMU for arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # We use buildx instead of regular build so we can take advantage of Docker layer cache via GithubActions's cache
      # Also buildx offers multi-arch builds
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # the arm64 is of course much slower due to qemu, so build and push amd64 **first**
      # due to the way manifests work, the gap between this and the complete push below
      #  could result in pull failures or inconsistencies for arm64, such is life.
      # further duplicated by building both release and debug builds
      - name: Build and push amd64 Release Docker Image to DockerHub
        uses: docker/build-push-action@v6
        with:
          build-args: DEBUG_BUILD=0
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: rpardini/nginx-proxy-connect-stable-alpine:latest
          push: true

      - name: Build and push amd64 Debug Docker Image to DockerHub
        uses: docker/build-push-action@v6
        with:
          build-args: DEBUG_BUILD=1
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: rpardini/nginx-proxy-connect-stable-alpine:latest-debug
          push: true

      # Do it all again with both archs. the amd64 will be a huge cache hit
      # this will update the manifest have both arches
      - name: Build and push multiarch Release Docker Image to DockerHub
        uses: docker/build-push-action@v6
        with:
          build-args: DEBUG_BUILD=0
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: rpardini/nginx-proxy-connect-stable-alpine:latest
          push: true

      - name: Build and push multiarch Debug Docker Image to DockerHub
        uses: docker/build-push-action@v6
        with:
          build-args: DEBUG_BUILD=1
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: rpardini/nginx-proxy-connect-stable-alpine:latest-debug
          push: true

